[package]
name = "cfn-guard-rulegen"
version = "0.6.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.9"
log = "0.4.6"
clap = "2.33.0"
simple_logger = "1.3.0"
