[package]
name = "cfn-guard-rulegen-lambda"
version = "0.6.0"
edition = "2018"

[dependencies]
lambda_runtime = "0.2.1"
serde = "1.0.92"
serde_derive = "1.0.92"
simple-error = "0.2.0"
simple_logger = "1.3.0"
log = "0.4.6"
cfn-guard-rulegen = { path = "../cfn-guard-rulegen" }
