name: Typescript Library CI
on:
  push:
    paths:
    - 'guard/ts-lib/**'
  pull_request:
    paths:
    - 'guard/ts-lib/**'
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./guard
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm config set registry "https://registry.npmjs.com/"
      - run: npm install
      - run: npm test
